### ISSUE TITLE
Is WASI-IO an IoC scheme?

### ISSUE THREAD

**Issue by ProdigySim** [WebAssembly/wasi-io#11]
Curious newbie here, but I had a reason to research WASM recently and I watched [this talk](https://www.youtube.com/watch?v=k3HDivg3xyc) and a few others, and have been thinking about it.

The talk describes about changing programs from taking `argv/argc` and accessing global resources, to accepting higher level interface objects (`Stream`) as arguments and only having access to them. I can't help but think that this has parallels to IoC/dependency injection schemes. A function is written that takes a number of typed parameters, and an outer system is responsible for building & providing those typed arguments.

This sounds very intriguing; I can imagine an environment where applications are written to take higher-typed parameters, and the calling environment is responsible for producing them. 

e.g. 
`function main(input: ReadStream, output: WriteStream)` 
`$ copy(input: "file:///home/me/file.txt", output: "file:///tmp/file.txt")`

But I haven't found any search results from people discussing WASI or WASI-IO as a IoC scheme, so I was not sure if I was misunderstanding something. It sounds similar.

**Comment by sunfishcode** [comment]
Yes, [dependency injection](https://github.com/WebAssembly/component-model/blob/55deedb1b8026f0117a8ef3611c5e77425ba1bd3/design/high-level/UseCases.md#component-dependencies) is a broader feature of the [component model](https://github.com/WebAssembly/component-model/) that WASI is being designed to work with. The component model is designed so that APIs are always virtualizable, and dependency injection doesn't require adding separate layers of abstraction. And the I/O streams described here fit into that; when a piece of code is written to work with an I/O stream, it'll be automatically abstracted over the possible sources for the I/O.

**Comment by lukewagner** [comment]
Also: you can see some concrete examples of this in the [Component Examples](https://docs.google.com/presentation/d/11lY9GBghZJ5nCFrf4MKWVrecQude0xy_buE--tnO9kQ) presentation that was presented incrementally over the last couple WASI subgroup meetings.

**Comment by ProdigySim** [comment]
Thanks for the links, this is very cool. I'm excited for the future here :D

> Component Examples presentation

For the "configuring multiple instances" problem on slides 25-29, I wonder if there's an opportunity to combine this with DevOps tools like Terraform/Pulumi/Cloudformation to configure the dependencies to map instantiated components to underlying resources. In the realm of serverless/microservices this sounds like a unique opportunity to combine configuration of resource access controls & runtime components. That's where my thoughts have been wandering anyway.

Thanks for taking the time to show me around 🙇🏻

**Comment by lukewagner** [comment]
That's a really great point; I think you're right there is a kind of symmetry there.  In particular, I was just learning about Terraform's modules, which are parameterized, and [module blocks](https://www.terraform.io/docs/language/modules/syntax.html), which are analogous to [instance definitions](https://github.com/WebAssembly/module-linking/blob/main/design/proposals/module-linking/Explainer.md#instance-definitions) in Module Linking (including, critically, the ability for a single child module to be instantiated multiple times with different arguments within a single deployment).

Where the symmetry breaks down a bit (at least in my mind) is that instantiating a component graph produces an ephemeral instance graph (with each instance containing linear memories and function tables that disappear if anyone traps or the hardware crashes) whereas instantiating ("applying") a Terraform-module graph produces persistent state.  I think what this shows is that ML-style-parameterized-modules is a pattern that can (and I think *should*) be applied in many different contexts.  But given that persistence is one of the explicit [non-goals](https://github.com/WebAssembly/component-model/blob/main/design/high-level/Goals.md#non-goals) of the component model, it's harder for me to see how the component model could concretely be applied to the domain of Infrastructure-as-Code.

**Comment by ProdigySim** [comment]
Rather than applying the component model to the domain of Infra-as-Code, I'm thinking of leveraging Infra-As-Code solutions to accomplish the configuration of the component mapping for final WASM applications. I think combining the two could potentially obviate the need for the Role-based access controls we currently use in cloud applications to restrict access to network resources.

This is pretty off topic, but essentially in microservice architectures I've seen, we [define cloud resource access controls in na infra-as-code file](https://gist.github.com/ProdigySim/ef175ce4983603f39542aa0f7010235d). This is not very DRY--we have already written a program that should only touch some set of Resources/APIs, and we have to analyze and extract that information into the cloud security policy.

I'm imagining that the component-injection model of WASI could allow developers to get the same resource-access-control guarantees without having to rely on network resource policy rules like these.

Given a simple [upload-to-s3](https://gist.github.com/ProdigySim/6a3b03878279269bebd61b829bbf71de) application, here's some [pulumi-style](https://www.pulumi.com/) pseudocode Infra-as-code to contrast with the one I linked before.
```typescript
const bucket = new aws.s3.Bucket("file-uploads", { acl: "private" });

const wasiApplication = new WasiTsApplication("./upload-to-s3.ts", {
  components: [
      new wasi.components.S3Bucket(bucket.id),  // <-- component which may only operate on a specific piece of infra
      wasi.components.crypto,
  ],
});
const uploadToS3App = new aws.lambda.Function("upload-to-s3", {
    code: wasiApplication,
    runtime: "wasm",
});
```

If an API like this was possible, it could render the network resource policy-writing unnecessary--at least for the infrastructures I've witnessed. As long as the security of those components could be relied upon, there would be no way for the application runtime to access other resources. But also, I think a similar API could be built without using WASI specifically--it's primarily the consistent DI scheme that enables this kind of API. One could write a tool to extract & produce a RBAC policy from an API like this.

Just brainstorming and getting excited to imagine what's possible with WASI in the future :) I don't know if this kind of potential use case will be valuable to your design work in any way, but thanks for entertaining the discussion.

**Comment by lukewagner** [comment]
Ah hah, I see what you were getting at; thanks for the clear example!  I think that's a fantastic point and a perfect way to leverage the explicit parameterization of wasm modules.  It also highlights, I think, the limitations of global-namespace-based designs, which in turn prompted the ["no global namespaces"](https://github.com/WebAssembly/component-model/blob/main/design/high-level/Choices.md) high-level design choice in the component model.

I agree that this doesn't seem so much like a thing WASI itself can specify, but rather something a Wasm/WASI *embedding* would need to adopt as its model for how Wasm modules/components are instantiated in the system.  One thing WASI *can* do, however, is design interfaces that lend themselves to this kind of instantiation-time wiring of individual capabilities.  So as a concrete example, this is a reason for WASI not to have a single all-powerful `open()` or `listen()` through which all resources are homogeneously accessed, because now we can't distinguish (in your example) S3 buckets from everything else.  In contrast, I think we want to have one function import (which is semantically an import of a closure over a *host capability*) per distinct capability.  You can see this concretely in the Component Examples where you have one imported `wasi:http/Backend` instance per endpoint that you can send requests to (e.g., [in this example](https://docs.google.com/presentation/d/11lY9GBghZJ5nCFrf4MKWVrecQude0xy_buE--tnO9kQ/edit#slide=id.gf59378ef96_0_46) there are two).
